package com.adchallenge.enums;

public enum EventNotificationErrorCode {
	SUBSCRIPTION_NOT_EDITABLE,
	USER_ALREADY_EXISTS,
	USER_NOT_FOUND,
	ACCOUNT_NOT_FOUND,
	MAX_USERS_REACHED,
	UNAUTHORIZED,
	OPERATION_CANCELED,
	CONFIGURATION_ERROR,
	INVALID_RESPONSE,
	PENDING,
	FORBIDDEN,
	BINDING_NOT_FOUND,
	TRANSPORT_ERROR,
	UNKNOWN_ERROR,
}
