package com.adchallenge.enums;

public enum EventType {
  SUBSCRIPTION_ORDER,
  SUBSCRIPTION_CHANGE,
  SUBSCRIPTION_CANCEL,
  SUBSCRIPTION_NOTICE,
  USER_ASSIGNMENT,
  USER_UNASSIGNMENT,
  USER_UPDATED,
  UNKNOWN
}
